const V=require('../src/engine.js'),a=require('assert');let n=0,t=(name,f)=>{f();console.log('ok',name)},A=(...x)=>{a(...x);n++};
t('similarity guard',()=>{A(!V.ok('sponge','spongebob'));A(!V.ok('pizza','pizza'));A(!V.ok('water','wat'));A(V.ok('sponge','water'))});
t('pool integrity',()=>{const all=[];for(const c in V.WORDS)for(const w in V.WORDS[c]){A(V.ok(w,V.WORDS[c][w]),w);all.push(w)}A(new Set(all).size===all.length)});
t('validation',()=>{a.throws(()=>V.validate(0,5));a.throws(()=>V.validate(5,5));a.throws(()=>V.validate(1,2));A(V.validate(2,5)===2)});
t('roles',()=>{const s=V.newRound(['a','b','c','d','e'],{imposters:2,seed:7});A(V.cnt(s).imp===2&&V.cnt(s).inn===3);A(s.hint)});
t('no hints',()=>A(V.newRound(['a','b','c'],{imposters:1,hints:false,seed:1}).hint===null));
t('empty pool is error',()=>a.throws(()=>V.newRound(['a','b','c'],{imposters:1,cats:[]},[])));
t('votes',()=>{const r=V.resolveVotes(['a','b','c'],{a:'b',b:'b',c:null});A(r.out==='b');const t2=V.resolveVotes(['a','b'],{a:'b',b:'a'});A(!t2.out&&t2.tied.length===2);A(!V.resolveVotes(['a','b'],{}).out);A(!V.resolveVotes(['a','b','c'],{a:'c',b:'c'},['a','b']).out)});
t('win/parity beats guess',()=>{const s=V.newRound(['a','b','c'],{imposters:1,seed:3});const imp=s.players.find(p=>s.roles[p]==='imposter'),inn=s.players.filter(p=>p!==imp);A(V.eliminate(s,inn[0])==='imposters')});
t('last imposter guess',()=>{const mk=()=>V.newRound(['a','b','c','d'],{imposters:1,seed:5}),s=mk(),imp=s.players.find(p=>s.roles[p]==='imposter');A(V.eliminate(s,imp)==='guess');A(V.guess(s,s.word)==='imposters');const s2=mk();V.eliminate(s2,imp);A(V.guess(s2,'zzz')==='innocents')});
t('guess disabled',()=>{const s=V.newRound(['a','b','c','d'],{imposters:1,guessing:false,seed:5});A(V.eliminate(s,s.players.find(p=>s.roles[p]==='imposter'))==='innocents')});
console.log(n+' assertions passed');
